dist: xenial
language: python
python: 3.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  - "pip install -U pip"
  - "pip install Lektor"

script: "lektor build -v"

deploy:
  provider: script
  script: "lektor deploy ghpages"
  on:
    branch: master
